/**
 * Opal scripting engine — ambient global type definitions.
 *
 * SOURCE OF TRUTH: generated by hand from the Opal scripting docs
 * (`resources/docs/en/scripting/**`). Every member below corresponds to a
 * documented `<Method>` tag or documented table entry — signatures, params,
 * and return types are not invented.
 *
 * This file ships inside the "Opal Scripting" VS Code extension
 * (`opalclient.opal-scripting`). On activation the extension copies it into
 * the open workspace as `.vscode/opal.d.ts` so plain `.js` files under
 * `opal/scripts/` get IntelliSense for every ambient global the Opal
 * GraalVM JS engine injects at runtime — `client`, `player`, `world`,
 * `renderer`, `notification`, `overlay`, `modules`, `mc`, `movement`,
 * `rotation`, `inventory`, `esp`, `palette`, `keys`, `registerScript`, and
 * the bound Java/wrapper types (`BlockPos`, `Vec2f`, `Color`, `MAIN_HAND`, …).
 *
 * There is no `import`/`require` step for any of this at runtime — the
 * engine injects these names directly into the script's global scope. This
 * file mirrors that by declaring everything as ambient globals (no top-level
 * `import`/`export`, which is what keeps TypeScript treating it as a global
 * script rather than a module).
 *
 * Scripts run sandboxed (GraalVM `HostAccess.EXPLICIT`): only members
 * explicitly annotated `@HostAccess.Export` on the proxy globals below, plus
 * a small JDK allow-list, are reachable from script code — see `intro.mdx`.
 * This file only describes the *shape* of that exposed API, not the sandbox
 * boundary itself.
 */

/* ============================================================================
 * Bound Java interop types (see Java Interop table in intro.mdx / world/types.mdx)
 * ========================================================================== */

/**
 * `net.minecraft.world.phys.Vec3`, bound as `Vec3d`. A raw Minecraft type —
 * its instance methods are Fabric-intermediary-named at runtime and are
 * **not** callable by readable name from a script. Construct it and pass it
 * into proxy methods (e.g. `esp.projectVec`, `rotation.getRotationFromPosition`);
 * read coordinates back through the proxy that produced it, or via
 * `player.getBlockPosition()` for a readable wrapper.
 */
interface Vec3d {
    /** Opaque — do not call instance methods directly; see class doc comment. */
    readonly __opalVec3dBrand?: never;
}
declare const Vec3d: {
    /** Constructs a new world-space double vector. */
    new (x: number, y: number, z: number): Vec3d;
};

/**
 * `net.minecraft.core.Vec3i`, bound as `Vec3i`. Same intermediary-name
 * caveat as `Vec3d` — treat as construct-and-pass-through only. Prefer
 * `BlockPos` for block positions (it exposes readable `getX/getY/getZ`).
 */
interface Vec3i {
    readonly __opalVec3iBrand?: never;
}
declare const Vec3i: {
    new (x: number, y: number, z: number): Vec3i;
};

/**
 * A yaw/pitch rotation pair. Bound as `Vec2f`, backed by the `ScriptVec2f`
 * wrapper around `net.minecraft.world.phys.Vec2`. Unlike `Vec3d`, this
 * wrapper's methods ARE readable-name-callable.
 */
interface Vec2f {
    /** Yaw angle (horizontal rotation) in degrees. */
    getYaw(): number;
    /** Pitch angle (vertical rotation) in degrees. */
    getPitch(): number;
}
declare const Vec2f: {
    new (yaw: number, pitch: number): Vec2f;
};

/**
 * An integer block position. Bound as `BlockPos`, backed by the
 * `ScriptBlockPos` wrapper around `net.minecraft.core.BlockPos`. Returned by
 * proxies such as `player.getBlockPosition()`.
 */
interface BlockPos {
    getX(): number;
    getY(): number;
    getZ(): number;
    /** Returns a new BlockPos shifted one block in the given direction. */
    offset(direction: Direction): BlockPos;
}
declare const BlockPos: {
    new (x: number, y: number, z: number): BlockPos;
};

/** Lowercase cardinal/vertical direction name returned by `Direction.getName()`. */
type DirectionName = "north" | "south" | "east" | "west" | "up" | "down";

/**
 * A cardinal or vertical facing direction. Backed by the `ScriptDirection`
 * wrapper around `net.minecraft.core.Direction`. Scripts do not construct
 * this directly — obtain one from `world.getAdjacentDirections(pos)`.
 */
interface Direction {
    /** The direction opposite to this one (e.g. NORTH to SOUTH, UP to DOWN). */
    getOpposite(): Direction;
    /** Lowercase direction name. */
    getName(): DirectionName;
}

/**
 * A validated rotation paired with the hit result needed for block or entity
 * interaction. Backed by `ScriptRaytracedRotation`. Returned by
 * `rotation.getRotationFromRaycastedBlock()` and
 * `rotation.getRotationFromRaycastedEntity()`. May be `null` when no valid
 * rotation reaches the target — always null-check the result.
 */
interface RaytracedRotation {
    /** Yaw angle in degrees to aim at the target. */
    getYaw(): number;
    /** Pitch angle in degrees to aim at the target. */
    getPitch(): number;
    /** Raw hit result — pass to `mc.interactionManager.interactBlock()`. */
    getHitResult(): HitResult;
}

/** `net.minecraft.util.Mth`, bound as `MathHelper`. Its static methods are
 * intermediary-named at runtime and are NOT callable by readable name. For
 * interpolation use `esp.lerp(start, end, tickDelta)`; for general math
 * prefer JavaScript's built-in `Math`. Kept opaque intentionally. */
declare const MathHelper: unknown;

/**
 * The standard `java.awt.Color`, bound as `Color`. Unlike the Minecraft
 * wrapper types above, its methods are NOT intermediary-mapped, so they are
 * callable directly. An alternative to `renderer.color(r, g, b, a)` for
 * building packed ARGB integers.
 */
interface JavaColor {
    /** Packed ARGB integer for this color, suitable for any renderer color parameter. */
    getRGB(): number;
}
declare const Color: {
    new (r: number, g: number, b: number, a?: number): JavaColor;
};

/** `net.minecraft.world.InteractionHand` constant — pass to hand parameters. */
interface InteractionHand {
    readonly __opalInteractionHandBrand?: never;
}
/** The player's main hand. */
declare const MAIN_HAND: InteractionHand;
/** The player's off hand. */
declare const OFF_HAND: InteractionHand;

/** A generic 2D double vector, e.g. the `from`/`to` params of `movement.getMoveYaw(from, to)`. */
interface Vector2d {
    x: number;
    y: number;
}

/** Screen-space projection result from `esp.project` / `esp.projectVec`. */
interface Vector3d {
    /** Screen X coordinate. */
    x: number;
    /** Screen Y coordinate. */
    y: number;
    /** Depth — a value `>= 1.0` means the point is behind the camera. */
    z: number;
}

/** Screen-space rectangle from `esp.getEntityBox2D` (packed x/y/width/height). */
interface Vector4d {
    /** Left edge of the 2D box (screen X). */
    x: number;
    /** Top edge of the 2D box (screen Y). */
    y: number;
    /** Width of the 2D box. */
    z: number;
    /** Height of the 2D box. */
    w: number;
}

/** Raw hit-result object. Opaque — obtain from `RaytracedRotation.getHitResult()`
 * and pass straight to `mc.interactionManager.interactBlock()`. */
interface HitResult {
    readonly __opalHitResultBrand?: never;
}

/** A Minecraft text component. `.getString()` yields the plain-text form. */
interface TextComponent {
    getString(): string;
}

/** Raw Minecraft entity (from `world.getEntities()` or
 * `world.getLivingEntitiesInRange()`). Opaque aside from the documented
 * member below — `attack`'s target is exposed via `AttackEvent`'s own
 * primitive getters (`getTargetName()`, `getTargetId()`, ...) rather than a
 * raw `Entity`. */
interface Entity {
    getName(): TextComponent;
}
/** A living entity (mob or player). */
interface LivingEntity extends Entity {}

/** Opaque item stack, from `inventory.getStack()` / `getMainHandStack()` / `getOffHandStack()`. */
interface ItemStack {
    readonly __opalItemStackBrand?: never;
}
/** Opaque block state, from `world.getBlockState()` / block-update event getters. */
interface BlockState {
    readonly __opalBlockStateBrand?: never;
}
/** Opaque block type, from `world.getBlock()`. */
interface Block {
    readonly __opalBlockBrand?: never;
}
/** Axis-aligned bounding box, from `player.getBoundingBox()`. Also referred to as `Box` in some docs. */
interface AABB {
    readonly __opalAabbBrand?: never;
}
/** Alias — `interaction.mdx` calls this type `Box`, `player.mdx` calls it `AABB`. Same object. */
type Box = AABB;
/** Opaque server address, from `serverConnect`'s `getServerAddress()`. */
interface ServerAddress {
    readonly __opalServerAddressBrand?: never;
}
/** Opaque frame draw context, from render-event `drawContext()`. */
interface GuiGraphicsExtractor {
    readonly __opalGuiGraphicsExtractorBrand?: never;
}
/** Opaque render canvas / bloom target, from render-event `canvas()`. */
interface RenderCanvas {
    readonly __opalRenderCanvasBrand?: never;
}
/** Opaque camera-relative transform stack, from `renderWorld`'s `matrixStack()`. */
interface PoseStack {
    readonly __opalPoseStackBrand?: never;
}

/**
 * A `java.util.List` as seen from script code. Supports the accessor style
 * used throughout the docs (`list.get(i)`, `list.isEmpty()`, `list.size()`)
 * as well as `for (const x of list)` iteration. Some lists (e.g. the return
 * of `renderer.wrapText`) are documented as also behaving like a plain JS
 * array (`.length`, `list[i]`); this interface allows both styles.
 */
interface JavaList<T> extends Iterable<T> {
    readonly length: number;
    readonly [index: number]: T;
    get(index: number): T;
    size(): number;
    isEmpty(): boolean;
}

/**
 * Packed 32-bit ARGB color integer. **Always build these with
 * `renderer.color(r, g, b[, a])` / `Color` / `withAlpha` / `interpolate`
 * rather than a raw `0xAARRGGBB` literal** — JavaScript numbers are a single
 * 64-bit `double`, and a hex literal with alpha `>= 0x80` is larger than
 * `2^31`; narrowing it to a Java `int` truncates to the wrong value.
 */
type ARGBColor = number;

/** GPU-resident image handle from `renderer.loadImage()`. */
interface GpuImageHandle {
    /** Whether this handle refers to a successfully loaded image. */
    isValid(): boolean;
}
declare const GpuImageHandle: {
    /** Sentinel returned by `loadImage` on failure — always `isValid() === false`. */
    readonly NONE: GpuImageHandle;
};

/** Registered font names accepted by every `renderer` text method. Bare
 * string literals from other font packs are still accepted at runtime. */
type FontName = "productsans-bold" | "productsans-medium" | "materialicons-regular" | (string & {});

/* ============================================================================
 * keys — GLFW key codes (palette-view key handlers; see ui/palette.mdx)
 * ========================================================================== */

/**
 * GLFW key codes as plain integer fields, since scripts cannot reference
 * `org.lwjgl.*` classes directly. Values match the codes the command
 * palette delivers to `keyPressed(keyCode, mods)`.
 */
interface KeysGlobal {
    UP: number;
    DOWN: number;
    LEFT: number;
    RIGHT: number;
    SPACE: number;
    ENTER: number;
    ESCAPE: number;
    TAB: number;
    BACKSPACE: number;
    LEFT_SHIFT: number;
    LEFT_CONTROL: number;
    A: number; B: number; C: number; D: number; E: number; F: number; G: number;
    H: number; I: number; J: number; K: number; L: number; M: number; N: number;
    O: number; P: number; Q: number; R: number; S: number; T: number; U: number;
    V: number; W: number; X: number; Y: number; Z: number;
    NUM_0: number; NUM_1: number; NUM_2: number; NUM_3: number; NUM_4: number;
    NUM_5: number; NUM_6: number; NUM_7: number; NUM_8: number; NUM_9: number;
}
declare const keys: KeysGlobal;

/* ============================================================================
 * timer — stopwatch helper (reference/core.mdx "Timer Proxy")
 * ========================================================================== */

/** Stopwatch handle returned by `timer.create()`. Tracks elapsed time since
 * the last `reset()` (or since creation, if never reset). */
interface Stopwatch {
    /** Resets the elapsed-time baseline to now. */
    reset(): void;
    /** Milliseconds elapsed since the last `reset()` (or creation). */
    elapsed(): number;
    /** Whether at least `ms` milliseconds have elapsed since the last reset. */
    passed(ms: number): boolean;
    /** `passed(ms)`, and if true, also resets the baseline — the common
     * "has enough time gone by? if so, restart the clock" rate-limit check. */
    passedAndReset(ms: number): boolean;
}

interface TimerProxy {
    /** Creates a new stopwatch, its baseline starting at the moment of creation. */
    create(): Stopwatch;
    /** Current engine time in milliseconds — a raw timestamp, not tied to any stopwatch. */
    now(): number;
}
declare const timer: TimerProxy;

/* ============================================================================
 * Events (events.mdx) — payload objects passed to module.on(name, handler)
 * ========================================================================== */

/** Base shape shared by every cancellable event. Calling `setCancelled()` on
 * a non-cancellable event throws, since the method does not exist on that
 * payload — only call it on events documented as cancellable. */
interface CancellableEvent {
    /** Marks the event cancelled. Cannot be un-set once called. */
    setCancelled(): void;
    /** Whether the event has already been cancelled by another handler. */
    isCancelled(): boolean;
}

/** `enable/disable` lifecycle events receive no argument at all. */
type NoPayload = undefined;

/** Fired at the start of a tick, before vanilla tick logic runs. Carries no data. */
interface PreGameTickEvent {}
/** Fired at the end of a tick, after vanilla tick logic has run. Carries no data. */
interface PostGameTickEvent {}

/** `renderScreen` — fired during the 2D HUD pass. A record; use bare accessors. */
interface RenderScreenEvent {
    /** The GUI graphics extractor for the current frame. */
    drawContext(): GuiGraphicsExtractor;
    /** The render canvas for the pass. */
    canvas(): RenderCanvas;
    /** Cursor X position in GUI-scaled coordinates. */
    mouseX(): number;
    /** Cursor Y position in GUI-scaled coordinates. */
    mouseY(): number;
    /** Fractional progress through the current tick (0.0–1.0), for smooth interpolation. */
    tickDelta(): number;
}

/** `renderWorld` — fired during the 3D world pass. Use `esp.*` for projection here. */
interface RenderWorldEvent {
    /** Camera-relative transform stack (pre-multiplied by the camera view rotation). */
    matrixStack(): PoseStack;
    /** Partial tick (0.0–1.0). */
    tickDelta(): number;
}

/** `renderBloom` — fired during the HUD bloom pass. Shapes drawn here feed
 * the glow/bloom effect rather than showing directly. */
interface RenderBloomEvent {
    /** The GUI graphics extractor for the current frame. */
    drawContext(): GuiGraphicsExtractor;
    /** The bloom render target for this pass. */
    canvas(): RenderCanvas;
    /** Partial tick (0.0–1.0). */
    tickDelta(): number;
}

/** `preMove` / `postMove` payload. Cancellable only on `preMove`. */
interface PreMoveEvent extends CancellableEvent {
    /** Movement speed for the step. */
    getSpeed(): number;
    /** Directional movement input vector for the step. */
    getMovementInput(): Vec3d;
}
interface PostMoveEvent {
    getSpeed(): number;
    getMovementInput(): Vec3d;
}

/** `preMovementPacket` — before the movement packet is sent. Getters read the
 * values about to be sent; setters rewrite them before the packet leaves
 * (server-side position/rotation spoofing). Cancellable — note the accessor
 * names (`isCancelled()` / `cancel()`) are distinct from the older
 * `CancellableEvent.setCancelled()` shape used by `preMove`/`serverConnect`;
 * the two event families are not interchangeable. */
interface PreMovementPacketEvent {
    getX(): number;
    getY(): number;
    getZ(): number;
    setX(x: number): void;
    setY(y: number): void;
    setZ(z: number): void;
    getYaw(): number;
    getPitch(): number;
    setYaw(yaw: number): void;
    setPitch(pitch: number): void;
    isOnGround(): boolean;
    setOnGround(onGround: boolean): void;
    isSprinting(): boolean;
    setSprinting(sprinting: boolean): void;
    isHorizontalCollision(): boolean;
    setHorizontalCollision(horizontalCollision: boolean): void;
    /** Whether the packet is sent even when no movement occurred. */
    isForceInput(): boolean;
    /** Forces the packet to be sent even when no movement occurred. */
    setForceInput(forceInput: boolean): void;
    /** Whether the event has already been cancelled by another handler. */
    isCancelled(): boolean;
    /** Cancels the event — the movement packet is dropped and never sent. Cannot be un-set once called. */
    cancel(): void;
}

/** `postMovementPacket` — read-only subset describing what was actually sent.
 * No setters, not cancellable. */
interface PostMovementPacketEvent {
    getX(): number;
    getY(): number;
    getZ(): number;
    getYaw(): number;
    getPitch(): number;
    isOnGround(): boolean;
    isSprinting(): boolean;
}

/** Shared payload for all four packet events — cancelling drops the packet
 * so vanilla never sends/handles it. Note the accessor names (`isCancelled()`
 * / `cancel()`) are distinct from the older `CancellableEvent.setCancelled()`
 * shape used by `preMove`/`serverConnect`. */
interface PacketEvent {
    /** Simple class name of the wrapped packet, e.g. `"ServerboundMovePlayerPacket"`. */
    getType(): string;
    /** Whether the event has already been cancelled by another handler. */
    isCancelled(): boolean;
    /** Cancels the event — the packet is dropped and never sent/handled. Cannot be un-set once called. */
    cancel(): void;
}
/** A packet is about to be sent to the server. Cancellable. */
interface SendPacketEvent extends PacketEvent {}
/** A packet is received from the server, before it is handled. Cancellable. */
interface ReceivePacketEvent extends PacketEvent {}
/** An outbound packet is sent immediately on the network thread. Cancellable. */
interface InstantaneousSendPacketEvent extends PacketEvent {}
/** An inbound packet is received on the network thread, before main-thread queueing. Cancellable. */
interface InstantaneousReceivePacketEvent extends PacketEvent {}

/** `attack` — the player attacks an entity, before the interaction is processed. Not cancellable. */
interface AttackEvent {
    /** Display name of the entity being attacked. */
    getTargetName(): string;
    /** Entity id of the target. */
    getTargetId(): number;
    /** Target's current health, or `-1` if the target is not a living entity. */
    getTargetHealth(): number;
    /** Target's maximum health, or `-1` if the target is not a living entity. */
    getTargetMaxHealth(): number;
    /** Distance to the target, or `-1` if unavailable. */
    getTargetDistance(): number;
}

/** `swing` — a record; read fields with bare accessors, no `get` prefix. Not cancellable. */
interface SwingEvent {
    /** The hand performing the swing. */
    hand(): InteractionHand;
}

/** `itemUse` — the player uses (right-clicks) the held item. Carries no data. Not cancellable. */
interface ItemUseEvent {}

/** `jump` — before the jump impulse is applied. Cancellable — note the
 * accessor names (`isCancelled()` / `cancel()`) are distinct from the older
 * `CancellableEvent.setCancelled()` shape used by `preMove`/`serverConnect`. */
interface JumpEvent {
    /** Whether the player is sprinting while jumping. */
    isSprinting(): boolean;
    /** Overrides whether the jump is treated as a sprint jump, changing the forward boost applied. */
    setSprinting(sprinting: boolean): void;
    /** Whether the event has already been cancelled by another handler. */
    isCancelled(): boolean;
    /** Cancels the event — the jump impulse never applies. Cannot be un-set once called. */
    cancel(): void;
}

/** `joinWorld` — the local player joins a world, after the client world is initialised. Carries no data. */
interface JoinWorldEvent {}

/** `blockUpdate` — a loaded block changes state. Not cancellable. */
interface BlockUpdateEvent {
    /** Position where the block change occurred. */
    getPos(): BlockPos;
    /** Block state before the update. */
    getOldState(): BlockState;
    /** Block state after the update. */
    getNewState(): BlockState;
}

/** `serverConnect` — before connecting to a multiplayer server. Cancel to abort the connection. */
interface ServerConnectEvent extends CancellableEvent {
    /** The address being connected to. */
    getServerAddress(): ServerAddress;
}

/** `serverDisconnect` — the client disconnects from a server. Carries no data. */
interface ServerDisconnectEvent {}

/** `chatReceived` — a chat message is received from the server, before it is shown. Cancellable —
 * note the accessor names (`isCancelled()` / `cancel()`) are distinct from the older
 * `CancellableEvent.setCancelled()` shape used by `preMove`/`serverConnect`. */
interface ChatReceivedEvent {
    /** The received chat message as plain text. */
    getMessage(): string;
    /** Whether the message is an action-bar overlay message rather than a chat-line message. */
    isOverlay(): boolean;
    /** Reroutes the message to (true) or away from (false) the action bar. */
    setOverlay(overlay: boolean): void;
    /** Whether the event has already been cancelled by another handler. */
    isCancelled(): boolean;
    /** Cancels the event — the message is never shown. Cannot be un-set once called. */
    cancel(): void;
}

/** Shared shape of `keyPress` / `mousePress` — both expose the GLFW code through the same accessor. */
interface InteractionCodeEvent {
    /** GLFW key code (keyPress) or mouse button code (mousePress) that triggered the event. */
    getInteractionCode(): number;
}
/** `keyPress` — a keyboard key is pressed. Not cancellable. */
interface KeyPressEvent extends InteractionCodeEvent {}
/** `mousePress` — a mouse button is pressed. Not cancellable. */
interface MousePressEvent extends InteractionCodeEvent {}

/** `resolutionChange` — the GUI is resized (framebuffer resolution changed). Carries no data. Not cancellable. */
interface ResolutionChangeEvent {}

/* ============================================================================
 * registerScript / registerModule (intro.mdx, events.mdx, settings.mdx)
 * ========================================================================== */

interface ScriptMetadata {
    /** Script display name. */
    name: string;
    /** Semantic version string, e.g. "1.0.0". Max 16 characters when published. */
    version: string;
    /** Author name(s) shown on the public Scripts page. */
    authors: string[];
}

interface ModuleMetadata {
    /** Module display name — appears in the ClickGUI alongside native modules. */
    name: string;
    /** Short description of what the module does. */
    description: string;
}

/**
 * The event-name -> handler map for `module.on(...)`. `enable`/`disable`
 * receive no argument; every other event receives its documented payload
 * object. There is one handler slot per event name per module — calling
 * `on` again with the same name replaces the previous handler.
 */
interface ScriptModuleEvents {
    enable: () => void;
    disable: () => void;
    preGameTick: (event: PreGameTickEvent) => void;
    postGameTick: (event: PostGameTickEvent) => void;
    renderScreen: (event: RenderScreenEvent) => void;
    renderWorld: (event: RenderWorldEvent) => void;
    renderBloom: (event: RenderBloomEvent) => void;
    preMove: (event: PreMoveEvent) => void;
    postMove: (event: PostMoveEvent) => void;
    preMovementPacket: (event: PreMovementPacketEvent) => void;
    postMovementPacket: (event: PostMovementPacketEvent) => void;
    sendPacket: (event: SendPacketEvent) => void;
    receivePacket: (event: ReceivePacketEvent) => void;
    instantaneousSendPacket: (event: InstantaneousSendPacketEvent) => void;
    instantaneousReceivePacket: (event: InstantaneousReceivePacketEvent) => void;
    attack: (event: AttackEvent) => void;
    swing: (event: SwingEvent) => void;
    itemUse: (event: ItemUseEvent) => void;
    jump: (event: JumpEvent) => void;
    joinWorld: (event: JoinWorldEvent) => void;
    blockUpdate: (event: BlockUpdateEvent) => void;
    serverConnect: (event: ServerConnectEvent) => void;
    serverDisconnect: (event: ServerDisconnectEvent) => void;
    chatReceived: (event: ChatReceivedEvent) => void;
    keyPress: (event: KeyPressEvent) => void;
    mousePress: (event: MousePressEvent) => void;
    resolutionChange: (event: ResolutionChangeEvent) => void;
}

/**
 * The `module` object passed into a `registerModule` callback. Exposes the
 * event registration API (`on`) plus the settings API (`addBool`,
 * `addNumber`, `addMode`, `addGroup`, and their `get`/`set` counterparts).
 * All settings must be defined synchronously inside the callback, before
 * any `module.on(...)` calls — they are finalized once the callback returns.
 */
interface ScriptModule {
    /**
     * Registers a callback for a named event. The callback receives the
     * event object as its only argument (lifecycle events receive nothing).
     * Calling `on` again with the same event name replaces the previous
     * handler rather than stacking.
     */
    on<K extends keyof ScriptModuleEvents>(event: K, handler: ScriptModuleEvents[K]): void;
    /** Escape hatch for an event name not covered by `ScriptModuleEvents`. */
    on(event: string, handler: (event: any) => void): void;

    /** Adds a boolean (toggle) setting. Appears as a switch in the ClickGUI. */
    addBool(name: string, defaultValue: boolean): void;
    /** Adds a numeric (slider) setting. Appears as a slider in the ClickGUI. */
    addNumber(name: string, defaultValue: number, min: number, max: number, step: number): void;
    /** Adds a mode (dropdown) setting. `options` is a plain JS string array; the first option is the default. */
    addMode(name: string, options: string[]): void;
    /**
     * Groups one or more previously defined settings under a collapsible
     * header. Call this AFTER the settings it references — names that
     * don't match an already-added setting are ignored, and if none match,
     * the group is not created.
     */
    addGroup(name: string, settingNames: string[]): void;

    /** Current value of a boolean setting, or `false` if it doesn't exist. */
    getBool(name: string): boolean;
    /** Sets a boolean setting's value. No-ops if the setting doesn't exist. */
    setBool(name: string, value: boolean): void;
    /** Current value of a numeric setting, or `0.0` if it doesn't exist. */
    getNumber(name: string): number;
    /** Sets a numeric setting's value. No-ops if the setting doesn't exist. */
    setNumber(name: string, value: number): void;
    /** Currently selected option of a mode setting, or `""` if it doesn't exist. */
    getMode(name: string): string;
    /** Whether a mode setting currently equals `option` (case-insensitive). There is no `setMode` — mode settings are read-only from script code. */
    isModeEqual(name: string, option: string): boolean;
}

/** Handle returned by `registerScript()`, used to register one or more modules. */
interface ScriptHandle {
    /**
     * Registers a module (feature toggle) that appears in the ClickGUI
     * alongside native modules, with its own settings and event handlers.
     */
    registerModule(config: ModuleMetadata, callback: (module: ScriptModule) => void): void;
}

/**
 * Every script entry point must register itself with `registerScript`. This
 * is the only true top-level global function — everything else scripts do
 * happens through the returned handle or the ambient proxy globals below.
 */
declare function registerScript(metadata: ScriptMetadata): ScriptHandle;

/* ============================================================================
 * client — core/client (reference/core.mdx "Client Proxy")
 * ========================================================================== */

/** Opaque handle to a registered module, from `client.getModule(id)`. */
interface ModuleHandle {
    readonly __opalModuleHandleBrand?: never;
}

interface ClientProxy {
    /** Prints a message to the local chat only. Calls `toString()` on the object. */
    print(o: unknown): void;
    /** Prints a success-styled (green) message to the local chat. */
    success(message: string): void;
    /** Prints an error-styled (red) message to the local chat. */
    error(message: string): void;

    /** Retrieves a registered module by display name (case-insensitive). Throws if not found. */
    getModule(id: string): ModuleHandle;
    /** Whether a specific module is currently enabled. */
    isModuleEnabled(id: string): boolean;
    /** Toggles a module on or off. */
    setModuleEnabled(id: string, enabled: boolean): void;

    /** Sends a chat message to the server, exactly as if typed in the chat box. */
    sendChat(message: string): void;
    /** Runs a client command. The leading `/` is optional — `"toggle Fly"` and `"/toggle Fly"` both work. */
    runCommand(command: string): void;

    /** Width of the game window in scaled virtual pixels (affected by GUI scale). */
    getScaledWidth(): number;
    /** Height of the game window in scaled virtual pixels. */
    getScaledHeight(): number;
    /** Current GUI scale factor (e.g. 1.0, 2.0). */
    getScaleFactor(): number;
    /** Raw physical width of the window in pixels. */
    getFramebufferWidth(): number;
    /** Raw physical height of the window in pixels. */
    getFramebufferHeight(): number;

    /** Primary color of the active client theme as an ARGB integer. */
    getThemePrimary(): ARGBColor;
    /** Secondary color of the active client theme as an ARGB integer. */
    getThemeSecondary(): ARGBColor;
    /**
     * Interpolates between the primary and secondary theme colors in a
     * pulsing animation. Use `offset` to create gradients/waves across
     * multiple elements.
     */
    getAnimatedThemeColor(speed: number, offset: number): ARGBColor;

    /** Partial tick time (0.0 to 1.0) for smooth rendering interpolation between ticks. */
    getTickDelta(): number;
    /** Current frames per second. */
    getFPS(): number;
}
declare const client: ClientProxy;

/* ============================================================================
 * notification — core/notifications (reference/core.mdx "Notification Proxy")
 * ========================================================================== */

interface NotificationProxy {
    /** Displays a green success toast notification. `duration` is in ms (default 3000). */
    success(title: string, description: string, duration?: number): void;
    /** Displays a red error toast notification. */
    error(title: string, description: string, duration?: number): void;
    /** Displays a yellow warning toast notification. */
    warn(title: string, description: string, duration?: number): void;
    /** Displays a blue informational toast notification. */
    info(title: string, description: string, duration?: number): void;
    /** Displays a notification with a dynamic type string. */
    show(type: "SUCCESS" | "ERROR" | "WARN" | "INFO", title: string, description: string, duration?: number): void;
}
declare const notification: NotificationProxy;

/* ============================================================================
 * overlay — core/overlay (reference/core.mdx "Overlay Proxy")
 * ========================================================================== */

interface IslandConfig {
    /** Island content width. */
    width: number;
    /** Island content height. */
    height: number;
    /** Render priority — higher renders on top. */
    priority: number;
    /** Draws one frame of the island's content. */
    render(posX: number, posY: number, width: number, height: number, progress: number): void;
}

interface OverlayProxy {
    /** Creates a new Dynamic Island and returns its unique ID. */
    createIsland(config: IslandConfig): string;
    /** Activates the island, adding it to the render loop. */
    showIsland(islandId: string): void;
    /** Deactivates the island without destroying it. */
    hideIsland(islandId: string): void;
    /** Permanently deletes the island. */
    destroyIsland(islandId: string): void;
    /** Updates the content width dynamically. */
    setIslandWidth(islandId: string, width: number): void;
    /** Updates the height dynamically. */
    setIslandHeight(islandId: string, height: number): void;
    /** Updates the render priority (higher renders on top). */
    setIslandPriority(islandId: string, priority: number): void;
}
declare const overlay: OverlayProxy;

/* ============================================================================
 * modules — core/modules.mdx
 * ========================================================================== */

/** Module category, accepted case-insensitively by `listCategory`. */
type ModuleCategory = "Combat" | "Movement" | "Visual" | "World" | "Utility" | "Scripts" | (string & {});

interface ModulesProxy {
    /** Whether a module with the given name is registered. */
    exists(id: string): boolean;
    /** Whether a module is currently enabled. `false` if it doesn't exist. */
    isEnabled(id: string): boolean;
    /** Enables or disables a module by name. No-ops silently if not found. */
    setEnabled(id: string, enabled: boolean): void;
    /** Toggles a module on or off by name. No-ops silently if not found. */
    toggle(id: string): void;

    /** Category name of a module (e.g. 'Combat', 'Movement'), or `null` if not found. */
    getCategory(id: string): string | null;
    /** Arraylist suffix of a module (often the current mode), or `null`. */
    getSuffix(id: string): string | null;
    /** Whether a module is visible in the arraylist/HUD. */
    isVisible(id: string): boolean;
    /** Sets whether a module should be visible in the arraylist/HUD. */
    setVisible(id: string, visible: boolean): void;

    /** Display names of all registered modules, both native and script-defined. */
    listAll(): string[];
    /** Display names of all modules in the given category. */
    listCategory(category: ModuleCategory): string[];
    /** Display names of all currently enabled modules. */
    listEnabled(): string[];
}
declare const modules: ModulesProxy;

/* ============================================================================
 * mc — MinecraftProxy (reference/mc.mdx, reference/core.mdx)
 * ========================================================================== */

/** Local player entity as seen through `mc.player`. Null-check use only —
 * for real state/behaviour use the `player` proxy global instead. */
interface LocalPlayer {
    readonly __opalLocalPlayerBrand?: never;
}
/** Client world as seen through `mc.world`. Null-check use only — for real
 * block/entity queries use the `world` proxy global instead. */
interface ClientLevel {
    readonly __opalClientLevelBrand?: never;
}

/**
 * Handles block interactions, entity attacks, and block breaking. Every
 * method is null-guarded internally, so it is safe to call before the
 * world or player are ready.
 */
interface InteractionManagerProxy {
    /** Right-clicks a block face. `hitResult` comes from `RaytracedRotation.getHitResult()`. */
    interactBlock(hand: InteractionHand, hitResult: HitResult): void;
    /** Begins or updates block-breaking progress on the given face. Returns whether progress was updated. */
    updateBlockBreakingProgress(blockPos: BlockPos, direction: Direction): boolean;
    /** Cancels any in-progress block breaking. */
    cancelBlockBreaking(): void;
    /** Whether a block break is currently in progress. */
    isBreakingBlock(): boolean;
    /** Attacks an entity with the local player's main hand. */
    attackEntity(entity: Entity): void;
    /** Uses the item in the given hand (right-click use, not on a block). */
    interactItem(hand: InteractionHand): void;
    /** Stops using an item (e.g. releasing a bow or stopping eating). */
    stopUsingItem(): void;
}

/**
 * A safe, structured facade over the Minecraft client. `mc.player` and
 * `mc.world` exist for **null checks only** — for actual player/world
 * behaviour use the dedicated `player`/`world`/`inventory` proxy globals,
 * which return script-safe wrapper types instead of raw Fabric-intermediary
 * objects. `mc.player === null` is the idiomatic guard at the top of every
 * event callback.
 */
interface MinecraftProxy {
    /** Null-check field — local player entity, or `null` if not yet loaded. */
    readonly player: LocalPlayer | null;
    /** Null-check field — active client world, or `null` if not yet loaded. */
    readonly world: ClientLevel | null;
    /** Block/entity interaction proxy. */
    readonly interactionManager: InteractionManagerProxy;

    /** Method form of the `player` field. Intended for null-guard checks only. */
    getPlayer(): LocalPlayer | null;
    /** Method form of the `world` field. Intended for null-guard checks only. */
    getWorld(): ClientLevel | null;
    /** Method form of the `interactionManager` field. Prefer the field directly. */
    getInteractionManager(): InteractionManagerProxy;
}
declare const mc: MinecraftProxy;

/* ============================================================================
 * player — character/player.mdx
 * ========================================================================== */

/**
 * Local player state: position, rotation, health, combat utilities, and
 * basic actions. Every method here reads from `mc.player`, which is `null`
 * on the main menu, during world loads, and between disconnects — guard
 * every handler with `if (mc.player === null) return;` before use.
 */
interface PlayerProxy {
    /** Player's eye position in world space — the origin point for raycasts and rotation calculations. */
    getEyePosition(): Vec3d;
    /** Alias of `getEyePosition()` — despite the name, this is also the eye position, not the feet. */
    getPosition(): Vec3d;
    /** Floored block coordinates the player is standing in, with readable `getX/getY/getZ`. */
    getBlockPosition(): BlockPos;
    /** Current per-tick velocity (delta movement) vector. */
    getVelocity(): Vec3d;
    /** Player's axis-aligned bounding box. */
    getBoundingBox(): AABB;
    /** Eye height above feet, in blocks. */
    getStandingEyeHeight(): number;

    /** Current yaw (horizontal) rotation in degrees. */
    getYaw(): number;
    /** Current pitch (vertical) rotation in degrees. */
    getPitch(): number;
    /** Distance fallen since last touching ground, in blocks. */
    getFallDistance(): number;

    /** Whether the player is currently on the ground. */
    isOnGround(): boolean;
    /** Whether the player is currently airborne. */
    isInAir(): boolean;
    /** Ticks spent in the air continuously. */
    getAirTicks(): number;
    /** Ticks spent on the ground continuously. */
    getGroundTicks(): number;
    /** Whether the player is sneaking (shift held). */
    isSneaking(): boolean;
    /** Whether the player is sprinting. */
    isSprinting(): boolean;
    /** Whether the player is using an item (eating, blocking, drawing a bow, etc.). */
    isUsingItem(): boolean;

    /** Current health points. */
    getHealth(): number;
    /** Maximum health points. */
    getMaxHealth(): number;
    /** Absorption (golden hearts) amount. */
    getAbsorption(): number;

    /** Whether the next attack would land a critical hit (falling, not on ground, not in water, etc.). */
    canCrit(): boolean;
    /** Attack damage of the item currently held in the main hand. */
    getAttackDamage(): number;
    /** Maximum distance, in blocks, at which the player can attack/interact with entities. */
    getEntityInteractionRange(): number;
    /** Whether the main-hand item is a weapon (sword, axe, or pickaxe). */
    isHoldingWeapon(): boolean;

    /** Distance (bounding-box edge to edge) to a living entity, or `-1.0` for a non-living entity. */
    getDistanceToEntity(entity: Entity): number;
    /** Closest point on a living entity's bounding box to the player's eye — the point KillAura aims at. `null` for a non-living entity. */
    getClosestPoint(entity: Entity): Vec3d | null;
    /** Whether the player's box, shifted by the given offset, is free of collidable blocks. */
    isBoxEmpty(offsetX: number, offsetY: number, offsetZ: number): boolean;
    /** Whether the space directly below the player (at the given Y offset, typically negative) is empty. */
    isBoxEmptyBelow(offsetY: number): boolean;

    /** Plays the hand swing animation for the given hand. */
    swingHand(hand: InteractionHand): void;
    /** Right-clicks (uses) the item in the given hand and plays the swing animation. */
    useItem(hand: InteractionHand): void;
}
declare const player: PlayerProxy;

/* ============================================================================
 * movement — character/movement.mdx
 * ========================================================================== */

interface MovementProxy {
    /** Current horizontal speed in blocks per second. Roughly `getSpeed() * 20`. */
    getBlocksPerSecond(): number;
    /** Current horizontal speed as a raw velocity magnitude, in blocks per tick. */
    getSpeed(): number;
    /** Whether the player is currently providing movement input (WASD or equivalent). Reflects input keys, not actual velocity. */
    isMoving(): boolean;

    /** Sets horizontal speed using the current movement input direction. */
    setSpeed(speed: number): void;
    /**
     * Sets horizontal speed with either a strafe blend (0.0 forward .. 1.0
     * strafe) or a specific yaw in degrees — these are two distinct
     * documented overloads that collapse to the same call site because
     * JavaScript has only one number type. Test both behaviors in-game
     * before shipping a script that relies on this.
     */
    setSpeed(speed: number, strafePercentageOrYaw: number): void;
    /** Sets the velocity of an arbitrary entity along a given yaw direction. */
    setEntitySpeed(entity: Entity, speed: number, yaw: number): void;
    /** Applies the player's Swiftness potion-effect bonus to a base speed (optionally with a custom per-level multiplier). */
    getSwiftnessSpeed(speed: number, swiftnessMultiplier?: number): number;

    /** Movement yaw between two 2D positions. */
    getMoveYaw(from: Vector2d, to: Vector2d): number;
    /** Current movement yaw based on WASD input and camera rotation. */
    getMoveYaw(): number;
    /** Current movement direction in degrees (or for a specific yaw, if given), accounting for strafe/forward input. */
    getDirectionDegrees(yaw?: number): number;
    /** Current movement direction in radians (or for a specific yaw, if given). */
    getDirectionRadians(yaw?: number): number;
    /** Calculates the exact movement direction from raw input values. Returns radians. */
    getDirection(rotationYaw: number, moveForward: number, moveStrafing: number): number;
    /** X/Z offsets for a given yaw direction and distance: `[deltaX, deltaZ]`. */
    yawPos(yaw: number, value: number): [number, number];
}
declare const movement: MovementProxy;

/* ============================================================================
 * rotation — character/rotation.mdx
 * ========================================================================== */

interface RotationProxy {
    /** Submits a target rotation using an instant (snap) model, applied on the next movement packet with automatic movement correction. */
    set(yaw: number, pitch: number): void;
    /** Submits a target rotation using a linear (smooth) model, capped to `speed` degrees per tick. Resubmit every tick (e.g. from `preGameTick`) rather than once. */
    setSmooth(yaw: number, pitch: number, speed: number): void;

    /** Yaw/pitch needed to look at a world position from the player's current eye position. */
    getRotationFromPosition(pos: Vec3d): Vec2f;
    /** Yaw/pitch needed to look at the center of a specific block face. */
    getRotationFromBlock(blockPos: BlockPos, direction: Direction): Vec2f;
    /**
     * Raytraced rotation to a block face, validating that it would hit the
     * intended face within reach (the method Scaffold uses for placement).
     * Returns `null` if no valid rotation exists.
     */
    getRotationFromRaycastedBlock(blockPos: BlockPos, side: Direction, priorityRotations: Vec2f, playerPos: Vec3d): RaytracedRotation | null;
    /**
     * Raytraced rotation to a living entity, validating a hit within range
     * (the method KillAura uses). Returns `null` if no valid rotation exists.
     */
    getRotationFromRaycastedEntity(entity: LivingEntity, closestVector: Vec3d, entityInteractionRange: number): RaytracedRotation | null;
    /** Unit look vector for the given pitch/yaw. */
    getRotationVector(pitch: number, yaw: number): Vec3d;

    /** Current server-side rotation as managed by the rotation handler. */
    getRotation(): Vec2f;
    /** Total angular difference between two rotations, accounting for wrapping. */
    getRotationDifference(a: Vec2f, b: Vec2f): number;
    /** Raw cursor delta needed to achieve a rotation delta, accounting for Minecraft's sensitivity multiplier. */
    getCursorDelta(rotationDelta: number, sensitivityMultiplier: number): number;
    /** Patches a rotation to avoid constant-delta detection by applying small natural-looking jitter. */
    patchConstantRotation(rotation: Vec2f, prevRotation: Vec2f): Vec2f;
    /** Snaps a rotation value to the nearest one achievable by Minecraft's mouse sensitivity system. */
    getSensitivityModifiedRotation(original: number): number;
    /** Sent (server-side) rotation after sensitivity correction. */
    getSentRotation(original: Vec2f): Vec2f;
    /** Applies Minecraft's sensitivity curve to both axes of a rotation. */
    getSensitivityModifiedRotationVec(original: Vec2f): Vec2f;
    /** Converts a rotation to vanilla Minecraft mouse-look coordinates. */
    getVanillaRotation(original: Vec2f): Vec2f;
    /** Wraps a rotation value toward a target to avoid duplicate-angle detection. */
    getDuplicateWrapped(value: number, target: number): number;

    /** Angular offset between the player's look direction and the direction to an entity. */
    getEntityFOV(entity: Entity): number;
    /** Whether an entity falls within a field-of-view cone centered on the player's look direction (`fov` = half-angle in degrees, 180 = full sphere). */
    isEntityInFOV(entity: Entity, fov: number): boolean;
}
declare const rotation: RotationProxy;

/* ============================================================================
 * inventory — character/inventory.mdx
 * ========================================================================== */

/**
 * Hotbar slot switching (with silent/spoof variants), item searching, and
 * stack inspection. Hotbar slots are `0`–`8`; the full inventory is `0`–`35`
 * (hotbar `0`–`8`, main inventory `9`–`35`). All methods read `mc.player`
 * without a null guard — confirm the player exists first.
 */
interface InventoryProxy {
    /** Switches the selected hotbar slot normally — visible to client and server. */
    setSlot(slot: number): void;
    /** Switches the slot in default silent mode: server sees the change, client held-item render may be preserved. */
    setSlotSilent(slot: number): void;
    /** Switches the slot in full silent mode: fully spoofed — server sees the change, client keeps rendering the original item. */
    setSlotFullSilent(slot: number): void;
    /** Sends a raw selected-slot update packet for the given slot, forcing a switch for a single action within one tick. */
    sendSlotPacket(slot: number): void;
    /** Currently selected hotbar slot index (0-8). */
    getSelectedSlot(): number;

    /** Searches the hotbar (0-8) for a valid placeable block. Returns `-1` if none found. */
    findBlock(): number;
    /** Searches the hotbar (0-8) for an item whose display name contains `itemName` (case-insensitive). Returns `-1` if not found. */
    findItem(itemName: string): number;
    /** Searches the full inventory (0-35) for an item by display-name substring (case-insensitive). Returns `-1` if not found. */
    findItemInInventory(itemName: string): number;

    /** Item stack in the given hotbar slot. */
    getStack(slot: number): ItemStack;
    /** Main-hand item stack, resolved through the slot system (accounts for silent switching). */
    getMainHandStack(): ItemStack;
    /** Off-hand item stack. */
    getOffHandStack(): ItemStack;
    /** Whether the main-hand item is a placeable block. */
    isHeldItemBlock(): boolean;
    /** Whether the item in the given slot is a placeable block. */
    isBlock(slot: number): boolean;
    /** Display name of the item in the given slot, or `""` if empty. */
    getItemName(slot: number): string;
    /** Stack count of the item in the given slot. */
    getItemCount(slot: number): number;
    /** Total count of a specific item across the whole inventory (display-name substring, case-insensitive). */
    countItem(itemName: string): number;
    /** Total placeable blocks across the hotbar and off hand. */
    countBlocks(): number;
}
declare const inventory: InventoryProxy;

/* ============================================================================
 * world — world proxy (reference/world.mdx; world/world.mdx not yet split out)
 * ========================================================================== */

interface WorldProxy {
    /** Whether the block at the given position is air. */
    isAir(pos: BlockPos): boolean;
    /** Whether the block can be replaced (air, fluid, grass, etc.). */
    isReplaceable(pos: BlockPos): boolean;
    /** Whether the block is solid. */
    isSolid(pos: BlockPos): boolean;
    /** Localized display name of the block. */
    getBlockName(pos: BlockPos): string;
    /** Raw block state object. */
    getBlockState(pos: BlockPos): BlockState;
    /** Block type object. */
    getBlock(pos: BlockPos): Block;
    /** Breaking hardness; `-1` means unbreakable (bedrock). */
    getBlockHardness(pos: BlockPos): number;

    /** Whether any face-adjacent block is solid (placeable-against). */
    hasAdjacentBlock(pos: BlockPos): boolean;
    /** Directions where a solid neighbour exists. Can be empty. */
    getAdjacentDirections(pos: BlockPos): JavaList<Direction>;

    /** All entities in the world. */
    getEntities(): Iterable<Entity>;
    /** Living entities (mobs + players) within `radius` of the player, excluding self. */
    getLivingEntitiesInRange(radius: number): JavaList<LivingEntity>;

    /** World time in ticks. */
    getTime(): number;
    /** Time of day: 0 = sunrise, 6000 = noon, 12000 = sunset, 18000 = midnight. */
    getTimeOfDay(): number;
    /** Dimension identifier, e.g. `'minecraft:overworld'`. */
    getDimension(): string;
}
declare const world: WorldProxy;

/* ============================================================================
 * esp — world/esp.mdx
 * ========================================================================== */

/**
 * 3D-to-2D screen projection for custom ESP overlays, used from
 * `renderScreen` (or `renderWorld` for world-space work). Projection
 * methods return `null` when the target is off-screen or behind the
 * camera — always null-check before drawing. Pass `client.getTickDelta()`
 * as `tickDelta` to every method for smooth inter-tick interpolation.
 */
interface EspProxy {
    /** Projects an entity's full 3D bounding box onto the screen, returning the enclosing 2D rectangle. `null` if behind camera or fully off-viewport. */
    getEntityBox2D(entity: LivingEntity, tickDelta: number): Vector4d | null;
    /** Projects a single 3D world position onto the 2D screen. Check `result.z < 1.0` — `>= 1.0` means behind the camera. */
    project(worldX: number, worldY: number, worldZ: number, tickDelta: number): Vector3d | null;
    /** Convenience wrapper around `project()` for a `Vec3d` position. */
    projectVec(pos: Vec3d, tickDelta: number): Vector3d | null;

    /** Smoothly interpolated, camera-relative entity position between the previous and current tick. `null` for non-`LivingEntity` targets. */
    getInterpolatedPosition(entity: Entity, tickDelta: number): Vec3d | null;
    /** Linear interpolation: `start + (end - start) * tickDelta`. */
    lerp(start: number, end: number, tickDelta: number): number;

    /** Whether a world position projects to a visible on-screen location (in front of the camera and inside the viewport). */
    isOnScreen(worldX: number, worldY: number, worldZ: number, tickDelta: number): boolean;
    /** Whether any part of an entity's bounding box projects to visible screen coordinates. Equivalent to `getEntityBox2D` returning non-null. */
    isEntityOnScreen(entity: LivingEntity, tickDelta: number): boolean;
}
declare const esp: EspProxy;

/* ============================================================================
 * renderer — ui/renderer.mdx
 * ========================================================================== */

/** A rendering callback bracketed by a transform's save/restore — draws made
 * inside run under that transform only. */
type RenderContent = () => void;

/**
 * A complete 2D drawing API backed by the active divinity canvas. Every draw
 * call must run inside an active canvas frame: a module's `renderScreen`
 * callback, a command-palette view's `render`, or a Dynamic Island's
 * `render` callback. Outside an active frame, image draws are silently
 * skipped. Colors are packed ARGB integers — build them with
 * `renderer.color(r, g, b[, a])`, never a raw `0xAARRGGBB` literal.
 */
interface RendererProxy {
    /** Draws a filled rectangle. */
    rect(x: number, y: number, width: number, height: number, color: ARGBColor): void;
    /** Draws a filled rectangle with uniformly rounded corners. */
    roundedRect(x: number, y: number, width: number, height: number, radius: number, color: ARGBColor): void;
    /** Draws a filled circle. */
    circle(cx: number, cy: number, radius: number, color: ARGBColor): void;

    /** Draws a rectangle filled with a linear two-color gradient. `angleDegrees` sets the gradient direction. */
    rectGradient(x: number, y: number, width: number, height: number, color1: ARGBColor, color2: ARGBColor, angleDegrees: number): void;
    /** Draws a rounded rectangle filled with a linear two-color gradient. */
    roundedRectGradient(x: number, y: number, width: number, height: number, radius: number, color1: ARGBColor, color2: ARGBColor, angleDegrees: number): void;

    /** Draws a filled rectangle with an independently specified radius per corner. */
    roundedRectVarying(x: number, y: number, width: number, height: number, radiusTopLeft: number, radiusTopRight: number, radiusBottomRight: number, radiusBottomLeft: number, color: ARGBColor): void;
    /** Per-corner-radius rectangle filled with a linear two-color gradient. */
    roundedRectVaryingGradient(x: number, y: number, width: number, height: number, radiusTopLeft: number, radiusTopRight: number, radiusBottomRight: number, radiusBottomLeft: number, color1: ARGBColor, color2: ARGBColor, angleDegrees: number): void;

    /** Draws the outline (border only) of a rectangle. */
    rectOutline(x: number, y: number, width: number, height: number, thickness: number, color: ARGBColor): void;
    /** Draws the outline (border only) of a rounded rectangle. */
    roundedRectOutline(x: number, y: number, width: number, height: number, radius: number, thickness: number, color: ARGBColor): void;
    /** Outline of a rounded rectangle with an independently specified radius per corner. */
    roundedRectOutlineVarying(x: number, y: number, width: number, height: number, radiusTopLeft: number, radiusTopRight: number, radiusBottomRight: number, radiusBottomLeft: number, thickness: number, color: ARGBColor): void;
    /** Draws a filled rectangle together with a stroke (border) of a separate color. */
    rectStroke(x: number, y: number, width: number, height: number, strokeThickness: number, color: ARGBColor, strokeColor: ARGBColor): void;
    /** Draws a rectangle outline together with a separately colored inner stroke. */
    rectOutlineStroke(x: number, y: number, width: number, height: number, outlineThickness: number, strokeThickness: number, outlineColor: ARGBColor, strokeColor: ARGBColor): void;

    /** Draws a rectangle filled with an animated rainbow gradient. */
    rainbowRect(x: number, y: number, width: number, height: number): void;

    /** Draws a soft box shadow behind a rounded-rectangle footprint. */
    shadow(x: number, y: number, width: number, height: number, radius: number, blur: number, offsetX: number, offsetY: number, color: ARGBColor): void;
    /** Fills a rounded rectangle with the blurred backdrop captured behind the UI (frosted-glass effect). */
    blurFill(x: number, y: number, width: number, height: number, radius: number): void;
    /** `blurFill` with an independently specified radius per corner. */
    blurFillVarying(x: number, y: number, width: number, height: number, radiusTopLeft: number, radiusTopRight: number, radiusBottomRight: number, radiusBottomLeft: number): void;
    /** Fills a rounded rectangle with the glow (bloom) pass texture — a soft glow around bright content. */
    glowFill(x: number, y: number, width: number, height: number, radius: number): void;
    /**
     * Draws an inner glow along the inside edges of a rounded rectangle.
     * **Advanced and visually unverified** — no native Opal UI callers yet;
     * treat as experimental.
     */
    innerGlow(x: number, y: number, width: number, height: number, radius: number, spread: number, color: ARGBColor): void;

    /** Loads an image from the client's resource path, returning a cached GPU handle. Returns `GpuImageHandle.NONE` on failure — check `isValid()` before drawing. */
    loadImage(path: string): GpuImageHandle;
    /** Draws a loaded image within the given bounds with optional corner rounding. Skipped silently outside an active render pass. */
    image(handle: GpuImageHandle, x: number, y: number, width: number, height: number, radius: number): void;
    /** Draws a loaded image multiplied by a tint color — useful for recoloring icons or fading images. */
    imageTinted(handle: GpuImageHandle, x: number, y: number, width: number, height: number, radius: number, tint: ARGBColor): void;
    /** Releases a GPU image previously obtained from `loadImage` and frees its backend resources. */
    destroyImage(handle: GpuImageHandle): void;

    /** Begins a new custom vector path. Subsequent `moveTo`/`lineTo`/`quadTo`/`cubicTo` calls build it. */
    beginPath(): void;
    /** Moves the current path cursor without drawing a segment. */
    moveTo(x: number, y: number): void;
    /** Adds a straight line segment from the cursor to the given point. */
    lineTo(x: number, y: number): void;
    /** Adds a quadratic bezier curve through control point `(cx, cy)` to `(x, y)`. */
    quadTo(cx: number, cy: number, x: number, y: number): void;
    /** Adds a cubic bezier curve through two control points to `(x, y)`. */
    cubicTo(c1x: number, c1y: number, c2x: number, c2y: number, x: number, y: number): void;
    /** Sets the stroke color used by the next `stroke()` call. */
    strokeColor(color: ARGBColor): void;
    /** Sets the stroke width used by the next `stroke()` call. */
    strokeWidth(width: number): void;
    /** Strokes the current path using the active stroke color and width. */
    stroke(): void;
    /** Closes the current path by connecting its last point back to its first. */
    closePath(): void;

    /** Draws a line of text and returns its rendered advance width. */
    text(fontName: FontName, text: string, x: number, y: number, size: number, color: ARGBColor): number;
    /** Draws a line of text with a drop shadow and returns its advance width. */
    textShadow(fontName: FontName, text: string, x: number, y: number, size: number, color: ARGBColor): number;
    /** Draws a line of text filled with a horizontal two-color gradient. */
    textGradient(fontName: FontName, text: string, x: number, y: number, size: number, color1: ARGBColor, color2: ARGBColor): void;
    /** Measures the rendered width of a string without drawing it. */
    textWidth(fontName: FontName, text: string, size: number): number;
    /** Measures the rendered height of a string without drawing it. */
    textHeight(fontName: FontName, text: string, size: number): number;
    /** Wraps a string into lines that each fit within `width`. */
    wrapText(fontName: FontName, text: string, width: number, size: number): JavaList<string>;
    /** Trims a string to fit within `width`, appending an ellipsis if truncated. */
    trimText(fontName: FontName, text: string, width: number, size: number): string;

    /** Runs `content` under a uniform scale transform pivoted at the center of the given rectangle. */
    scale(factor: number, x: number, y: number, width: number, height: number, content: RenderContent): void;
    /** Translates the origin to the center of the given rectangle and rotates; `content` draws relative to the new origin. */
    rotate(degrees: number, x: number, y: number, width: number, height: number, content: RenderContent): void;
    /** Pushes a scissor/clip region, runs `content`, then pops it so nothing drawn inside escapes the clip bounds. */
    scissor(x: number, y: number, width: number, height: number, content: RenderContent): void;
    /** Sets the global alpha multiplier applied to all subsequent draws this frame (0.0 transparent .. 1.0 opaque). */
    globalAlpha(alpha: number): void;

    /** Packs r/g/b/a (0-255 each) into an ARGB integer. */
    color(r: number, g: number, b: number, a: number): ARGBColor;
    /** Packs r/g/b (0-255 each) into a fully opaque ARGB integer (alpha 255). */
    color(r: number, g: number, b: number): ARGBColor;
    /** Replaces the alpha channel of an ARGB color, preserving RGB. */
    withAlpha(color: ARGBColor, alpha: number): ARGBColor;
    /** Scales the alpha of an ARGB color by an opacity factor (0.0-1.0). */
    applyOpacity(color: ARGBColor, opacity: number): ARGBColor;
    /** Linearly interpolates between two ARGB colors (`factor` 0.0 = color1, 1.0 = color2). */
    interpolate(color1: ARGBColor, color2: ARGBColor, factor: number): ARGBColor;
    /** Darkens an ARGB color by the given factor. */
    darker(color: ARGBColor, factor: number): ARGBColor;
    /** Brightens an ARGB color by the given factor. */
    brighter(color: ARGBColor, factor: number): ARGBColor;
}
declare const renderer: RendererProxy;

/* ============================================================================
 * palette — ui/palette.mdx
 * ========================================================================== */

/** A footer key hint shown at the bottom of an open palette view. */
interface PaletteFooterHint {
    key: string;
    label: string;
}

/**
 * Configuration object for `palette.createView`. `id` and `render` are
 * required; everything else is optional. `Esc` always closes the view
 * before any handler sees it — a view can never trap the user.
 */
interface PaletteViewConfig {
    /** Unique view id. Passed to `openView` / `removeView`. */
    id: string;
    /**
     * Draws one frame into the content rectangle. Called once per frame
     * while the view is open. The canvas frame is already open and
     * scissor-clipped to `[x, y, x + w, y + h]` when this runs. `dt` is
     * wall-clock seconds since the previous frame (clamped to 0.1s max,
     * `0.0` on the very first frame) — multiply velocities by it for
     * framerate-independent motion.
     */
    render(x: number, y: number, w: number, h: number, dt: number): void;
    /** Display title shown in the palette list (searchable). Defaults to `id`. */
    title?: string;
    /** Sub-text shown beside the title. Defaults to `"Script view"`. */
    description?: string;
    /** Placeholder text shown in the search row while the view is open. */
    placeholder?: string;
    /** Footer key hints, e.g. `[{ key: "Space", label: "Start" }]`. */
    footer?: PaletteFooterHint[];
    /** Handles a key press. Compare `keyCode` against the `keys` global. Return `true` to consume. `Esc` never reaches this handler. */
    keyPressed?(keyCode: number, mods: number): boolean | void;
    /** Handles a typed character (text input). Return `true` to consume. */
    charTyped?(codepoint: number): boolean | void;
    /** Handles a click in content-local coordinates (origin = top-left of the content rect). Return `true` to consume. */
    mouseClicked?(localX: number, localY: number, button: number): boolean | void;
}

/**
 * Registers a custom command-palette view: a canvas-backed surface your
 * script draws and drives itself, hosted like a mini-app or game. A
 * callback that throws is reported to chat once and then suppressed.
 */
interface PaletteProxy {
    /** Creates and registers a view from a config object. Returns the view id, or `null` if the config was invalid. */
    createView(config: PaletteViewConfig): string | null;
    /** Opens the command palette directly into a previously registered view. Enables the command-palette module if needed. */
    openView(id: string): void;
    /** Unregisters a previously registered view so it no longer appears in the palette. */
    removeView(id: string): void;
}
declare const palette: PaletteProxy;
